Django/Articles/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

Django/Articles/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    
]

Django/Articles/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    
]

Django/Articles/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content
        

Django/Articles/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ('user', 'like_users', )

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('article', 'user', )

Django/Articles/articles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse

from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles,
    }
    return render(request, 'articles/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form':form,
    }
    return render(request, 'articles/create.html', context)

@require_safe
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user.is_authenticated:
        if request.user == article.user:
            article.delete()
            return redirect('articles:index')
    return redirect('articles:detail', article.pk)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect()
    context = {
        'form':form,
        'article':article,
    }
    return render(request, 'articles/update.html', context)

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        article = Article.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('articles:detail', article.pk)
    return redirect('accounts:login')

@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)

@require_POST
def likes(request, article_pk):
    if request.user.is_authenticated:
        article = Article.objects.get(pk=article_pk)
        if request.user in article.like_users.all():
            article.like_users.remove(request.user)
            is_liked = False
        else:
            article.like_users.add(request.user)
            is_liked = True
        context = {
            'is_liked': is_liked,
            'likes_count': article.like_users.count()
        }
        return JsonResponse(context)
    return redirect('accounts:login')

Django/Articles/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

Django/Articles/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <p><b>{{ article.user }}'s Article</b></p>
  <p>Title : {{ article.title }}</p>
  <p>Content : {{ article.content }}</p>
  <p>Created at {{ article.create_at }}</p>
  <p>Updated at {{ article.updated_at }}</p>
  <p>Likes : {{ article.like_users.all|length }}</p>
  {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">Update</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE">
    </form>
  {% endif %}
  <hr>
  <a href="{% url 'articles:index' %}">Back</a>
  <hr>
  <h4>Comments</h4>
  {% if comments %}
    <p>Number of comments : {{ comments|length }}</p>
  {% endif %}
  <ul>
    {% for comment in comments %}
      <li>
        {% if request.user == comment.user %}
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
          {{ comment.user }} - {{ comment.content }}
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
        {% else %}
        {{ comment.user }} - {{ comment.content }}
        {% endif %}
      </li>
    {% empty %}
      <li>There is no comment..</li>
    {% endfor %}
  </ul>
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }} 
      <input type="submit" value='write'>
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">Please login to write the comment.</a>
  {% endif %}
{% endblock content %}

Django/Articles/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Articles</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}">Article Create</a>
  {% endif %}
  <hr>
  {% for article in articles %}
    <p>
      <b>User : <a href="{% url 'accounts:profile' article.user.username %}">{{article.user}}</a></b>
    </p>
    <p>Title : {{article.title}}</p>
    <p>Content : {{article.content}}</p>
    <p>Likes : <span id = "likes-count-{{article.pk}}">{{ article.like_users.all|length }}</span></p>
    <div class='d-flex flex-row mb-3'>
      <form id="like-forms" data-article-id = "{{ article.pk }}" class='d-flex flex-row'>
        {% csrf_token %}
        {% if request.user in article.like_users.all %}
          <button type="submit" class="btn btn p-0" id="like-{{article.pk}}"><i id="Like-{{article.pk}}" class="fa-solid fa-heart btn" style="color: red;"></i></button>
          <!-- <input type="submit" value="좋아요 취소" id="like-{{article.pk}}"> -->
          {% else %}
          <button type="submit" class="btn btn m-0" id="like-{{article.pk}}"><i id="Like-{{article.pk}}" class="fa-regular fa-heart"></i></button>
          <!-- <input type="submit" value="좋아요" id="like-{{article.pk}}"> -->
        {% endif %}
      </form>
      <form action="{% url 'articles:detail' article.pk %}" class='d-flex flex-row'>
        <button type="submit" class="btn btn "><i class="fa-regular fa-comment allign-items-center"></i></button>
      </form>
    </div>
    <hr>
  {% endfor %}

{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const forms = document.querySelectorAll('#like-forms')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken').value
    forms.forEach((form) => {
      form.addEventListener('submit', function (event) {
        event.preventDefault()
        const articleId = event.target.dataset.articleId
        axios({
          method: 'post',
          url: `http://127.0.0.1:8000/articles/${articleId}/likes/`,
          headers: {'X-CSRFToken': csrftoken,},
        })
        .then((response) => {
          const isLiked = response.data.is_liked
          const likeBtn = document.querySelector(`#like-${articleId}`)
          if (isLiked === true) {
            // likeBtn.value = 'Unlike'
            likeBtn.setAttribute('type', 'submit')
            likeBtn.setAttribute('class', 'btn btn p-0')
            
            let iTag = document.querySelector(`#Like-${articleId}`)
            iTag.setAttribute('class', "fa-solid fa-heart btn")
            iTag.setAttribute('style',"color: red;")

            console.log('zz')
            
          } else {
            // likeBtn.value = 'Like'
            likeBtn.setAttribute('type', 'submit')
            likeBtn.setAttribute('class', 'btn btn m-0')

            let iTag = document.querySelector(`#Like-${articleId}`)
            iTag.setAttribute('class', "fa-regular fa-heart")
            iTag.setAttribute('style',"color: black;")

            console.log('z')
          }
          const likesCountTag = document.querySelector(`#likes-count-${articleId}`)
          const likesCount = response.data.likes_count
          likesCountTag.innerText = likesCount
        })    
        .catch((error) => {
          console.log(error.response)
        })
      })
    });
  </script>
{% endblock script %}

Django/Articles/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='update'>
  </form>
  <hr>
  <a href="{% url 'articles:detail' article.pk %}">back</a>
{% endblock content %}